runtime: python27
threadsafe: true
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
    python_version: 3.7
    
handlers:
- url: /static
  static_dir: static
- url: .*
  script: main.app
  
libraries:
  - name: ssl
    version: latest
